from pydantic import BaseModel, Field
from typing import List, Dict, Optional, Any

class DataEngineerOutput(BaseModel):
    """Contract for the Data Engineer's output."""
    python_code: str = Field(..., description="The executable Pandas/PySpark code to clean the data.")
    reasoning: str = Field(..., description="Explanation of the imputation and encoding strategies.")
    target_variable: str = Field(..., description="The name of the target variable column.")
    features: List[str] = Field(..., description="List of final feature columns.")

class ModelerOutput(BaseModel):
    """Contract for the Modeler's output."""
    python_code: str = Field(..., description="The executable Scikit-Learn/XGBoost training script.")
    reasoning: str = Field(..., description="Explanation of algorithm selection and hyperparameter limits.")
    algorithm_used: str = Field(..., description="The primary algorithm used (e.g., 'XGBoost', 'RandomForest').")
    metrics: Dict[str, float] = Field(..., description="The evaluation metrics generated by the model.")

class EvaluatorOutput(BaseModel):
    """Contract for the Evaluator's critique."""
    is_approved: bool = Field(..., description="True if the code passes validation, False if leakage or error is detected.")
    reasoning: str = Field(..., description="Detailed explanation of approval or exact reasons for rejection.")
    suggested_fixes: Optional[List[str]] = Field(default_callback=list, description="List of direct instructions for the Modeler or Data Engineer to fix.")
